### ISSUE TITLE
Clarification about cookies handeling

### ISSUE THREAD

**Issue by fedihamdi** [rihemansour/Facebook_Scraper#5]
Hello @rihemansour ,
Appreciate your work and would like to better understand the following:

**1. Cookie and auth Handling** : since in the geckodriver starts blank cahe free (Do i really need to click ? maybe I am impatient)

![image](https://github.com/rihemansour/Facebook_Scraper/assets/29822817/6ce7bb26-0a2a-4fdf-8379-735b6c2c42b9)

**2. Requirements**: 

Say that i dont want to use the package (as the repo itself is the package here) I want to proceed "manuellement" (no trust) i would appreciate an `requirements.txt` file

- [ ] A naive proposition : I used the `pireqs` python command to generate it
```beautifulsoup4==4.12.2

Pillow==10.1.0

python_dateutil==2.8.2

Requests==2.31.0

selenium==4.15.2

selenium_wire==5.1.0

setuptools==68.2.2

webdriver_manager==3.2.2 ```

**Comment by rihemansour** [comment]
For the first part , I’m going to check the problem because I didn’t get it while testing.
For the requirements they’re all in the setup.py

**Comment by fedihamdi** [comment]
To be more accurate I had the problem running the .ipynb cells.
I guess i didn't explain the second point, what I wanted to say is that I do not prefer to use `py setup.py install` since it will creat an `.egg` and move things to env\lib\site-packages. Instead I am opting `pip install -r requirements.txt` so that i can test only the notebook ?

**Comment by rihemansour** [comment]
If you prefer not to use python setup.py install and want to manage dependencies with a requirements.txt file, you can certainly do that. Your proposed requirements.txt file looks fine, but you might want to include version specifications for each package to ensure compatibility.
If the issues persists you can check also the original repository because it was the source of the requirements : https://github.com/shaikhsajid1111/facebook_page_scraper

**Comment by fedihamdi** [comment]
Thank you @rihemansour that solves it.
